language: node_js

before_install:
  - gem install github-pages --no-rdoc --no-ri

node_js: 
  - "0.10"
  - "0.11"

script: 
  - ./node_modules/.bin/gulp default
  - jekyll build

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
