language: ruby

before_install:
  - gem install github-pages --no-rdoc --no-ri

rvm:
- 2.1
script: jekyll build && htmlproof ./_site

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
